version: '3.8'

services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
